# Generated by Django 3.2.6 on 2022-02-25 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cayenne_decoder', '0003_payload_counter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataTypes',
            new_name='DataType',
        ),
    ]
